### PR TITLE
Mac compatibility

### LINKED ISSUE #37: Font specification won't work on Mac/Linux
Update font specification to check current platform and do something different if non-Windows.

### PR DESCRIPTION
**Pull request by nmpeterson**
Can confirm this code works on my Mac (with prior installation of [XQuartz](https://www.xquartz.org/)).

@sarahcmap can you test it on yours? And @MMenninger can you test on Linux?

Resolves #37.

### CODE REVIEW

**Comment by matthewstern** [comment]
I can confirm on a PC without Whitney that I got a PC-specific error re substituting Calibri. Sure looks like Calibri to me:

image

@MMenninger ?

**Comment by MMenninger** [comment]
Error : 'windowsFonts' is not an exported object from 'namespace:grDevices'
Error: unable to load R code in package ‘cmapplot’
Execution halted
ERROR: lazy loading failed for package ‘cmapplot’
* removing ‘/home/martin/R/x86_64-pc-linux-gnu-library/3.6/cmapplot’
Error: Failed to install 'cmapplot' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpIiFrj5/file612f4a903eb/cmapplot_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by nmpeterson** [comment]
@MMenninger what do you get if you run `.Platform$OS.type` in the R console?

**Comment by nmpeterson** [comment]
@MMenninger you could try using [this unofficial port of Github Desktop](https://github.com/shiftkey/desktop) if you want the GUI. Otherwise, from the command line, you can `cd` to the `cmapplot` directory and then run `git checkout mac-compatibility`. (You may need to `git pull` first.)

**Comment by MMenninger** [comment]
Ok - figured out how to install a branch. Note to self - use and @ as in output below. 

devtools::install_github("CMAP-REPOS/cmapplot@mac-compatibility")
Downloading GitHub repo CMAP-REPOS/cmapplot@mac-compatibility
✓  checking for file ‘/tmp/RtmpIiFrj5/remotes612f32900803/CMAP-REPOS-cmapplot-cfc63aa/DESCRIPTION’ ...
─  preparing ‘cmapplot’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'cmapplot/data/recessions.RData'
─  building 'cmapplot_0.0.0.9000.tar.gz'
   
Installing package into ‘/home/martin/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘cmapplot’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Warning in eval(exprs[i], envir) :
  CMAP theme will default to Arial on non-Windows platforms
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (cmapplot)

**Comment by MMenninger** [comment]
This makes the package work on my Linux machine

**Pull request merged**
