### PR TITLE
Improve recessions, and other tweaks

### PR DESCRIPTION
**Pull request by matthewstern**
Many changes to recessions and some other tweaks. But also I made this really complicated. All eyes welcome, but @nmpeterson your help and careful review is especially requested.

### The story
I've been working in branch 'improve-recessions.' I was ready to create a pull request. improve-recessions was behind master so I did a PR (#38) from master to improve-recessions. This generated some very small conflicts that needed to be resolved. However, in resolving those conflicts I accidentally merged all my changes into master (in [this commit](https://github.com/CMAP-REPOS/cmapplot/commit/e18de039b8abe50244d724b14a21f15e3f81f9be)).

This was NOT what I wanted to do, as this branch contains many changes and I was hoping for a careful review before it was merged. Using github desktop I reverted this commit (The [revert feature](https://help.github.com/en/desktop/contributing-to-projects/reverting-a-commit) is available in github desktop. The revert showed up as a [new commit](https://github.com/CMAP-REPOS/cmapplot/commit/0ca4bd50bbe4ac85fa22c2a4de8847a12e99c51c)). 

Here's where the fun begins--there were many commits on branch improve-recessions, all of which got committed to master. Even though it appears that master is *entirely reverted* from a code perspective (an obvious example of this is that master currently contains the `add_recessions.R` file and NOT the `geom_recessions.R` file), master still contains records of all the commits made to branch improve-recessions (well, all but the most recent).  

For example, here are a handful of commits from improve-recessions that show up in master right now, even after the code reversion:
image

So, what appears to be going on is that even though this PR (hopefully) contains many changes, it only appears to have tweaked NAMESPACE, cmap_gradients.Rd, and cmap_palettes.Rd. Ideally, upon merging, master will reflect the changes shown in this PR *as well as* all the changes described in the [reverted commit here](https://github.com/CMAP-REPOS/cmapplot/commit/e18de039b8abe50244d724b14a21f15e3f81f9be). But I don't actually know that it will.

I am not sure if this PR is the right move. I also considered reverting each improve-recessions commit that was added to master, but that seems to be introducing funky merge conflicts, which scared me off.

...I am so sorry.

### Actual changes
Small changes:
- A newer version of Roxygen pushed some minimal formatting changes across many man files
- Some tweaks to the way the recessions.RData file was constructed, and related tweaks to its man page.
- When adding multiple elements to a ggplot via a list, you are allowed to construct a list with NA entries that are ignored. It seems this is the preferred way of doing this, rather than constructing one element and turning it into a list if a second one is needed (I saw it on a hadley help page but I don't remember where). I updated @nmpeterson's geom_text_lastonly.R to use this method.
 
Large changes:
- add_recessions.R, containing the old functionality for recessions, has been removed. 
- geom_recessions.R and its related man file have been added. geom_recessions involves one exported function (geom_recessions), one internal function (filter_recessions), and two custom ggproto objects, GeomRecessions and GeomRecessionsText. The `draw_panel` and `draw_key` attributes of each are directly taken from GeomRect and GeomText, but the `required_aes`, `default_aes`, and `setup_data` attributes are custom.
- @nmpeterson you had an issue in `geom_text_lastonly` where the `...` aesthetic attributes were being passed to both the points and the text. I had the same issue here, and after doing a bunch of reading decided the best way to handle this was to create list arguments for each and append them to the ggplot layer params. Check out the code for `geom_recessions()`. I'm curious if you think it is a good solution--if so, we should keep these two situations parallel, yeah?

### CODE REVIEW

**Comment by nmpeterson** [comment]
For future reference: it's best to avoid doing pull requests to bring `master` updates into a feature branch. Rather, just do a merge from the GitHub Desktop app:

image

I might try to clean this up using command line git and look at the code later this weekend. If I don't do it this weekend, it might have to wait a few days into next week because I think I'll be pretty busy with Conformity modeling.

**Comment by nmpeterson** [comment]
If you'd like to try cleaning it up yourself, it should be possible to reset `master` to an earlier commit with the `git reset` command. [This page](https://jwiegley.github.io/git-from-the-bottom-up/3-Reset/4-doing-a-hard-reset.html) seems from a quick glance like a good starting point. But I understand if you don't want to dive into command line git.

**Comment by matthewstern** [comment]
Damn. I forgot about merge within the desktop version. That is totally my bad. I'd love to learn command line git but feel like this might be a sensitive moment to go experimenting?  Let me know if you get a chance to take a look this weekend. Thanks @nmpeterson.

**Comment by nmpeterson** [comment]
@matthewstern it appears you somehow applied your revert not only to master but also to `improve-recessions`, which is why this PR appeared to only modify a few files -- because it did! I have created a new branch called `improve-recessions-fix`, based on `master` in its current state (where the merge was correctly reverted), and then applied all of your changes from `improve-recessions` on top of it.

Here is what you should do:
1. Fetch the `improve-recessions-fix` branch from GitHub to your PC.
2. Verify that everything looks as you want it to, and do whatever testing you had done on `improve-recessions` before creating this PR.
3. Delete the local copy of `improve-recessions` from your PC (which is the only place it still exists) once you are satisfied that all your work is reflected in `improve-recessions-fix`.
4. Submit a *new* PR from `improve-recessions-fix`.

At that point, someone can review the clean PR. (I probably won't have a chance till at least Wednesday.)

WOOF.

**Comment by matthewstern** [comment]
Thank you @nmpeterson!

**Pull request closed without merging**
