### PR TITLE
Adtl sample data

### PR DESCRIPTION
**Pull request by tallishmatt**
1. corrects some sample datasets 
2. adds roxygen-generated man files for all datasets which include example ggplot code from sample_graphics.R. 
3. comments out the sample_graphics.R file so that the file doesn't produce errors during roxygen documentation. These are now in man files but will ideally be placed in an Rmd readme file.

### CODE REVIEW

**Comment by nmpeterson** [comment]
When I run `devtools::check()` on this, I get the following error (seemingly coming from R/data.R):

```
> checking examples ... ERROR
  Running examples in 'cmapplot-Ex.R' failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: cluster_jobchange
  > ### Title: Job change in CMAP region by cluster, 2001-17
  > ### Aliases: cluster_jobchange
  > ### Keywords: datasets
  > 
  > ### ** Examples
  > 
  > # A bar chart
  > ggplot(cluster_jobchange, aes(x = reorder(name, jobchange), y = jobchange, fill = category)) +
  +   geom_col() +
  +   coord_flip() +
  +   cmapplot::theme_cmap()
  Error in ggplot(cluster_jobchange, aes(x = reorder(name, jobchange), y = jobchange,  : 
    could not find function "ggplot"
  Execution halted
```

I don't know why it complains about `ggplot()` but not the other tidyverse functions referenced earlier in the file, like `read_excel()`...

**Comment by tallishmatt** [comment]
So I'm out of town tomorrow, just documenting what I've learned so far:

I'm unsure what the deal is here. @sarahcmap and I looked at this for a while. devtools::check actually evaluates the examples in the man files to make sure they work, which is cool but also over the top. One solution is probably to wrap all the examples in `dontrun{}` but theoretically these should be able to run. We checked bbplot, which has ggplot2 listed in DESCRIPTION but not imported in NAMESPACE--this parallels what we have in our package at the moment. 

Help welcome.

**Comment by sarahcmap** [comment]
I'm also out tomorrow, but here are a few links I think are relevant if anyone is working on it in the meantime: 
http://r-pkgs.had.co.nz/namespace.html#imports
http://r-pkgs.had.co.nz/description.html (Dependencies section)

**Comment by tallishmatt** [comment]
Changes made by Noel (Specifically, moving ggplot2 from Imports to Depends in DESCRIPTION (which forces the function to run `library(ggplot2)`) solved the problem we were previously having.

However, it created a new problem on my machine associated, I think, with @nmpeterson 's font-fix branch #18. 

I now get the following error on `devtools::check()`:

```
 Running examples in 'cmapplot-Ex.R' failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: economy_basic
  > ### Title: Basic regional economic stats in 2001 and 2017
  > ### Aliases: economy_basic
  > ### Keywords: datasets
  > 
  > ### ** Examples
  > 
  > # a grouped and stacked bar chart (via `interaction()`)
  > ggplot(economy_basic, aes(x = interaction(year, variable), y = value, fill = sector)) +
  +   geom_col(position = "fill") +
  +   scale_y_continuous(labels = scales::percent) +
  +   theme_cmap()
  Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) :
    font family 'Whitney Medium' not found in PostScript font database
  Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) :
    font family 'Whitney Medium' not found in PostScript font database
  Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) :
    font family 'Whitney Medium' not found in PostScript font database
  Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) :
    font family 'Whitney Medium' not found in PostScript font database
  Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) :
    font family 'Whitney Medium' not found in PostScript font database
...
...
```

**Comment by nmpeterson** [comment]
That looks like you don't have the "Whitney Medium" typeface installed. Can you verify?

**Comment by tallishmatt** [comment]
Looks like I do. Nonetheless, the function should probably eventually have a backup font...

image

**Comment by tallishmatt** [comment]
You are correct though that the dozens of errors that are generated (I only copied in the first few lines) all refer to Whitney Medium.

**Comment by nmpeterson** [comment]
What do you see as Whitney options when you run `View(sysfonts::font_files())`? (You probably have to install `sysfonts`.)

This is mine:
image

**Comment by tallishmatt** [comment]
I have the identical list to you when filtered for family=whitney.

Curious if you get the error when running `devtools::check()` on this branch?

**Comment by nmpeterson** [comment]
Yes, I do. The problem is originating in data.R, but not sure what the problem actually is...

**Comment by tallishmatt** [comment]
Adding `dontrun{}` around the example in `clusters_jobchange` pushes the reported error to `economy_basic`, so seems like the error is still in the examples.  Commenting out `+ theme_cmap()` pushes the error down as well. However, changing to `cmapplot::theme_cmap()` does not address the error.

**Comment by nmpeterson** [comment]
Given that data.R is just the documentation for the datasets, I think it's fine to just remove `+theme_cmap()` from all of the examples.

**Comment by tallishmatt** [comment]
My first response was "hooray for kicking the can down the road" but then again the code works when run in the console this seems like a reasonable answer. I'll implement.

**Comment by tallishmatt** [comment]
@nmpeterson everything should be good now. Will you confirm and merge?

Learning plenty about documentation... 
1. used `\dontrun{}` in one example circumstance that requires downloading a file from the internet (this is `recessions`).
2. used `\dontshow{library(dplyr)}` to enable pipes in an example without showing the `library()` line in the example (this is `traded_emp_by_race`).

**Pull request merged**
