### PR TITLE
Added some tasteful ASCII art to the readme

### PR DESCRIPTION
**Pull request by nmpeterson**
We don't have to merge this, but after fully going down the ASCII art rabbit hole last night while watching inauguration coverage, I added some to a comment at the top of the readme file. I'm totally open to suggestions/modifications/improvements or outright rejection.

### CODE REVIEW

**Review by dlcomeaux — APPROVED** [review]
I love it. 10/10 would approve again.

**Review by matthewstern — APPROVED** [review]
I love it. Don't forget to change the version number :-D

**Review by gritzenthaler — APPROVED** [review]
I love it <3

**Review by sarahcmap — APPROVED** [review]

**Comment by nmpeterson** [comment]
> I love it. Don't forget to change the version number :-D

@matthewstern version 2.0.0 sounds right for this update...

(But in all seriousness, I don't think this warrants even a minor version change?)

**Comment by matthewstern** [comment]
> 
> 
> (But in all seriousness, I don't think this warrants even a minor version change?)

No change necessary because you put it in documentation. Now, had you put it in script that impacted package functions....

(Yes, I was just joking!)

**Pull request merged**
