### PR TITLE
geom_text_lastonly() enhancements

### PR DESCRIPTION
**Pull request by nmpeterson**
Addresses the remaining enhancements (suggestions 1 & 4) in #24.

### CODE REVIEW

**Comment by matthewstern** [comment]
@nmpeterson how do you feel about me changing the name of this function to `highlight_last_point`?

**Comment by nmpeterson** [comment]
I'm not a fan of that idea. I feel it's important to keep the naming consistent with other `ggplot2` geoms, which indicates to users that it *is* a `ggplot2` geom and it *can* accept the common parameters like `color`, `size`, etc., as well as inherit parameters from a base `ggplot()` object. The current name also indicates its direct relationship to `geom_text`.

**Comment by matthewstern** [comment]
Fair enough. My concern is that the function can now also add a geom_point layer as well, so I felt like the reference to geom_text is potentially misleading. You're not worried about that?

**Comment by nmpeterson** [comment]
Not really, since that's not the default behavior and I think the `add_point` parameter name is pretty self-explanatory. The only thing of concern to me is that explicitly setting a `size` value affects both, but adding an optional `point_size` parameter would resolve that.

**Comment by matthewstern** [comment]
OK, sounds good.

**Pull request merged**
