### PR TITLE
Whitney support on macOS

### PR DESCRIPTION
**Pull request by nmpeterson**
Added the ability for macOS (and presumably Linux/Unix) to use Whitney, if it's installed. It works perfectly for me.

Hoping @sarahcmap can help test this out on her own computer before merging.

Note: After merging, I want to continue using this branch to get the pkgdown site built with Whitney (see #92), so please don't delete it.

### CODE REVIEW

**Comment by matthewstern** [comment]
@nmpeterson I'm curious if you've checked whether fonts are successfully embedded with PDF export? Just noticing the strange font names and recalling the annoyance of dealing with font names a few months ago.

**Comment by nmpeterson** [comment]
Also requesting @matthewstern review to make sure I didn't break anything on Windows...

**Comment by nmpeterson** [comment]
> @nmpeterson I'm curious if you've checked whether fonts are successfully embedded with PDF export? Just noticing the strange font names and recalling the annoyance of dealing with font names a few months ago.

I successfully exported a PDF and it loaded correctly on my system. I didn't do any interrogation of font names, etc., though. (This `X11Font()` calls don't use font names, per se; it's more like a set of instructions for the OS to locate a specific font.)

**Review by sarahcmap — APPROVED** [review]
It works for me! And I inspected the pdf font in Illustrator.

Screen Shot 2020-12-01 at 5 38 26 PM

**Review by matthewstern — APPROVED** [review]
This also works for me. I've updated to v1.0.0

**Pull request merged**
