### PR TITLE
Change case of PNG file extensions

### PR DESCRIPTION
**Pull request by nmpeterson**
On my PC, the file extensions were showing as uppercase. I used `git mv` on the command line to rename them as lowercase. Hopefully this resolves the issue (#129).

### CODE REVIEW

**Comment by nmpeterson** [comment]
After nuking the contents of `gh-pages-test` and re-running the pkgdown action, both sets of images (the originals in man/figures and the copied versions in reference/figures) are now displayed in GitHub with lowercase extensions. We may also have to nuke `gh-pages` when version 1.2 gets merged into master.

**Comment by matthewstern** [comment]
Looks to me like this addressed the issue:

The previewed render of the html page here...
https://htmlpreview.github.io/?https://github.com/CMAP-REPOS/cmapplot/blob/gh-pages-test/articles/finalize.html

...shows the image and looks for the file as a lowercase extension, which is available here...
https://raw.githubusercontent.com/CMAP-REPOS/cmapplot/gh-pages-test/man/figures/margins1.png


would you guys agree that we should remove the resource files linking merged via #132, as that seems likely to be superfluous?

**Comment by nmpeterson** [comment]
I think it's fine to leave it, just in case pkgdown's automatic detection stops working in the future for any reason. From [the docs](https://pkgdown.r-lib.org/reference/build_articles.html#external-files):

> pkgdown differs from base R in its handling of external files. When building vignettes, R assumes that vignettes are self-contained (a reasonable assumption when most vignettes were PDFs) and only copies files explicitly listed in .install_extras. pkgdown takes a different approach based on rmarkdown::find_external_resources(), and it will also copy any images that you link to. **_If for some reason the automatic detection doesn't work, you will need to add a resource_files field to the yaml metadata_**

**Review by matthewstern — APPROVED** [review]

**Comment by matthewstern** [comment]
> After nuking the contents of `gh-pages-test` and re-running the pkgdown action,

@nmpeterson did the rename not take effect until you nuked the branch?

**Comment by nmpeterson** [comment]
@matthewstern correct. `pkgdown::deploy_to_branch(clean = TRUE)` does not seem to work exactly as advertised.

**Comment by matthewstern** [comment]
> 
> 
> @matthewstern correct. `pkgdown::deploy_to_branch(clean = TRUE)` does not seem to work exactly as advertised.
> 
> **Edit:** to be clear, the rename of the files in man/figures was successful, but the copies in reference/figures remained uppercase until I nuked them.

It doesn't particularly matter, but it's worth noting that I don't believe the `reference/figures/margin#.png` file actually gets used. While the pkgdown site does look for things like our logo in that folder (`https://cmap-repos.github.io/cmapplot/reference/figures/logo.png`) the way we've constructed the html image tag for margins does not seem to get overwritten:

html tag in Rmd file:
``

link in pkgdown HTML file:
`https://cmap-repos.github.io/cmapplot/man/figures/margins1.PNG`

which is not not:
`https://cmap-repos.github.io/cmapplot/reference/figures/margins1.PNG`

it may be that there is a different/less complex way to specify the `img src` that would be interpreted differently by the pkgdown process.

**Pull request merged**
